import "~/styles/globals.css";
import "@uploadthing/react/styles.css";


import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import  TopNav  from "./_components/topnav";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";

export const metadata: Metadata = {
  title: "T3 gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

// function Topnav() {
//   return (
//     <nav className="flex items-center justify-between p-4 bg-blue-800 text-white">
//       <div>Gallery</div>
//       <div>Sign in</div>
//       </nav>
//   );
// }

export default function RootLayout({
  children,modal
}: Readonly<{ children: React.ReactNode;
  modal:React.ReactNode;
 }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${geist.variable}`}>
         <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
      <body >
        <div className="h-screen grid grid-rows-[auto,1fr]">
        <TopNav/><main className="overflow-y-scroll">{children}</main>
        </div>
        {modal}
        <div id="modal-root"/>
        </body>
    </html>
    </ClerkProvider>
  );
}
