import "~/styles/globals.css";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Topnav } from "./_components/topnav";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "T3 gallery",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

// function Topnav() {
//   return (
//     <nav className="flex items-center justify-between p-4 bg-blue-800 text-white">
//       <div>Gallery</div>
//       <div>Sign in</div>
//       </nav>
//   );
// }

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${geist.variable}`}>
      <body className="flex flex-col gap-4"><Topnav/>{children}</body>
    </html>
    </ClerkProvider>
  );
}
